version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.40.3
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - checkout
      - run:
          name: "Build Website With Hugo"
          command: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run:
          name: "Test Website"
          command:  htmlproofer ~/hugo/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - run:
          name: "Deploy Website if master branch"
          command: if [ "$CIRCLE_BRANCH" == "master" ]; then bash .circleci/deploy.sh $HUGO_BUILD_DIR; fi
